import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Foundations',
      collapsed: false,
      className: 'sidebar-cat-foundations',
      items: [
        {
          type: 'doc',
          id: 'intro',
          label: 'Introduction',
        },
        {
          type: 'doc',
          id: 'prerequisites',
          label: 'Prerequisites',
        },
        {
          type: 'doc',
          id: 'install',
          label: 'Installation & Setup',
        },
        {
          type: 'doc',
          id: 'plugins',
          label: 'Plugins',
        },
        {
          type: 'doc',
          id: 'mcp',
          label: 'MCP Servers',
        },
      ],
    },
    {
      type: 'category',
      label: 'The DayZ Workflow',
      collapsed: false,
      className: 'sidebar-cat-workflow',
      items: [
        {
          type: 'doc',
          id: 'dayz-modding',
          label: 'End-to-End Guide',
        },
        {
          type: 'doc',
          id: 'dayz-conventions',
          label: 'Rules & Conventions',
        },
        {
          type: 'doc',
          id: 'model-routing',
          label: 'Model Routing',
        },
      ],
    },
    {
      type: 'category',
      label: 'AI Agents',
      className: 'sidebar-cat-agents',
      items: [{type: 'autogenerated', dirName: 'agents'}],
    },
    {
      type: 'category',
      label: 'Skills & Tools',
      className: 'sidebar-cat-skills',
      items: [{type: 'autogenerated', dirName: 'skills'}],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: true,
      className: 'sidebar-cat-contributing',
      items: [
        {
          type: 'doc',
          id: 'architecture',
          label: 'Architecture',
        },
        {
          type: 'doc',
          id: 'contributing',
          label: 'Contributing',
        },
      ],
    },
  ],
};

export default sidebars;
