"""dayz-new-mod: Scaffold a new DayZ mod project under workspace/<ModName>/.

Author handle resolution: --author flag -> cache file -> interactive prompt -> fail.
The cache lives at .claude/local-memory/dayz-author.txt (gitignored, per-clone).

See SKILL.md for full usage.
"""
from __future__ import annotations

import argparse
import importlib.util
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from string import Template

# REPO_ROOT = where this skill ships from (plugin or template clone).
# PROJECT_DIR = user's project (where workspace/ and local-memory/ live).
REPO_ROOT = Path(__file__).resolve().parents[3]
PROJECT_DIR = Path(os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()).resolve()
WORKSPACE = PROJECT_DIR / "workspace"
LOCAL_MEMORY = PROJECT_DIR / ".claude" / "local-memory"
AUTHOR_CACHE = LOCAL_MEMORY / "dayz-author.txt"
PREFLIGHT = REPO_ROOT / ".claude" / "skills" / "dayz-preflight" / "preflight.py"
P_DRIVE = Path("P:\\")

# Module name -> vanilla path it ships with in dayz.gproj. We append the mod's
# corresponding script folder to each so Workbench compiles vanilla + mod
# together, matching the engine's per-module load behavior at runtime.
WORKBENCH_MODULE_INJECTIONS = {
    "game": "scripts/3_Game",
    "world": "scripts/4_World",
    "mission": "scripts/5_Mission",
}

NAME_PATTERN = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,63}$")

OK = "[OK]   "
WARN = "[WARN] "
FAIL = "[FAIL] "
INFO = "[INFO] "


def _load_preflight_module():
    spec = importlib.util.spec_from_file_location("dayz_preflight_module", PREFLIGHT)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load preflight module at {PREFLIGHT}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_preflight = _load_preflight_module()
find_dayz_tools = _preflight.find_dayz_tools


CONFIG_CPP_TEMPLATE = Template(
    """class CfgPatches
{
    class ${modname}
    {
        units[] = {};
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = {"DZ_Data"};
    };
};

class CfgMods
{
    class ${modname}
    {
        dir = "${modname}";
        picture = "";
        action = "";
        hideName = 1;
        hidePicture = 1;
        name = "${modname}";
        credits = "${author}";
        author = "${author}";
        authorID = "0";
        version = "1.0";
        extra = 0;
        type = "mod";

        dependencies[] = {"Game", "World", "Mission"};

        class defs
        {
            class gameScriptModule
            {
                value = "";
                files[] = {"${modname}/scripts/3_Game"};
            };
            class worldScriptModule
            {
                value = "";
                files[] = {"${modname}/scripts/4_World"};
            };
            class missionScriptModule
            {
                value = "";
                files[] = {"${modname}/scripts/5_Mission"};
            };
        };
    };
};
"""
)


README_TEMPLATE = Template(
    """# ${modname}

DayZ mod scaffold generated by `/dayz-new-mod`.

## Layout

- `config.cpp` — engine declarations (CfgPatches, CfgMods)
- `$$PBOPREFIX$$` — in-game data path (`${modname}`)
- `scripts/3_Game`, `scripts/4_World`, `scripts/5_Mission` — Enforce Script modules
- `data/` — models (.p3d), textures (.paa), materials (.rvmat)
- `gui/` — UI layouts (.layout) and controllers
- `workbench/` — Workbench project (`dayz.gproj`, `DayZSetting.xml`) preconfigured with this mod's script paths; open via `/dayz-launch-workbench --mod ${modname}`

## Conventions

See `.claude/skills/_shared/dayz-conventions.md` in the parent template repo for the full DayZ workflow (asset/config/script/server conventions, P:\\ requirements, build & deploy pipeline).

## Author

${author}
"""
)


def validate_name(name: str) -> None:
    if not NAME_PATTERN.match(name):
        sys.exit(
            f"{FAIL} Invalid mod name: {name!r}\n"
            "       Must start with a letter; letters, digits, underscores only; max 64 chars."
        )


def resolve_author(cli_value: str | None) -> str:
    if cli_value:
        author = cli_value.strip()
        if not author:
            sys.exit(f"{FAIL} --author cannot be empty.")
        AUTHOR_CACHE.parent.mkdir(parents=True, exist_ok=True)
        AUTHOR_CACHE.write_text(author + "\n", encoding="utf-8")
        return author

    if AUTHOR_CACHE.exists():
        cached = AUTHOR_CACHE.read_text(encoding="utf-8").strip()
        if cached:
            return cached

    if sys.stdin.isatty():
        print("First-time setup: what author handle should appear in your DayZ mods?")
        print("(Public name shown in mod descriptions; not your real name or git identity.)")
        try:
            value = input("Author handle: ").strip()
        except EOFError:
            value = ""
        if not value:
            sys.exit(f"{FAIL} No author handle provided.")
        AUTHOR_CACHE.parent.mkdir(parents=True, exist_ok=True)
        AUTHOR_CACHE.write_text(value + "\n", encoding="utf-8")
        return value

    rel = AUTHOR_CACHE.relative_to(PROJECT_DIR)
    sys.exit(
        f"{FAIL} No author handle available.\n"
        "       Run with --author 'YourHandle' (cached for future runs)\n"
        f"       or write your handle to {rel}."
    )


def scaffold(modname: str, author: str) -> Path:
    target = WORKSPACE / modname
    target.mkdir(parents=True)
    print(f"{OK} Created {target.relative_to(PROJECT_DIR)}/")

    (target / "config.cpp").write_text(
        CONFIG_CPP_TEMPLATE.substitute(modname=modname, author=author),
        encoding="utf-8",
    )
    print(f"{OK} config.cpp written (author: {author})")

    (target / "$PBOPREFIX$").write_text(modname, encoding="utf-8")
    print(f"{OK} $PBOPREFIX$ written")

    for sub in ("scripts/3_Game", "scripts/4_World", "scripts/5_Mission", "data", "gui"):
        folder = target / sub
        folder.mkdir(parents=True)
        (folder / ".gitkeep").write_text("", encoding="utf-8")
    print(f"{OK} Skeleton folders created")

    (target / "README.md").write_text(
        README_TEMPLATE.substitute(modname=modname, author=author),
        encoding="utf-8",
    )
    print(f"{OK} README.md written")

    scaffold_workbench(target, modname)

    return target


def scaffold_workbench(target: Path, modname: str) -> None:
    """Create workspace/<ModName>/workbench/ with a customized dayz.gproj + DayZSetting.xml.

    Copies the official files shipped with DayZ Tools (Bin/Workbench/) and
    injects the mod's script paths into the gproj so Workbench compiles
    vanilla + mod scripts together. If DayZ Tools can't be located, scaffolds
    the folder with a placeholder note and warns — the rest of the mod is
    still usable; the user can re-copy the files later.
    """
    workbench_dir = target / "workbench"
    workbench_dir.mkdir(parents=True)

    tools_root = find_dayz_tools()
    if tools_root is None:
        (workbench_dir / "README.md").write_text(
            "# Workbench files missing\n\n"
            "DayZ Tools was not detected when this mod was scaffolded, so the official\n"
            "`dayz.gproj` and `DayZSetting.xml` couldn't be copied here.\n\n"
            "Once DayZ Tools is installed, copy them manually from:\n"
            "  <DayZ Tools>\\Bin\\Workbench\\dayz.gproj\n"
            "  <DayZ Tools>\\Bin\\Workbench\\DayZSetting.xml\n",
            encoding="utf-8",
        )
        print(f"{WARN} workbench/ created without official files (DayZ Tools not detected)")
        return

    src_workbench = tools_root / "Bin" / "Workbench"
    src_gproj = src_workbench / "dayz.gproj"
    src_setting = src_workbench / "DayZSetting.xml"

    if not src_gproj.exists():
        print(f"{WARN} {src_gproj} missing — workbench/ scaffolded empty")
        return

    gproj_text = src_gproj.read_text(encoding="utf-8")
    gproj_text = inject_mod_paths_into_gproj(gproj_text, modname)
    gproj_text = rewrite_filesystem_block(gproj_text, modname)
    (workbench_dir / "dayz.gproj").write_text(gproj_text, encoding="utf-8")
    print(f"{OK} workbench/dayz.gproj written (mod paths + filesystem mounts injected)")

    if src_setting.exists():
        shutil.copyfile(src_setting, workbench_dir / "DayZSetting.xml")
        print(f"{OK} workbench/DayZSetting.xml copied")
    else:
        print(f"{WARN} {src_setting} missing — DayZSetting.xml not copied")


def rewrite_filesystem_block(text: str, modname: str) -> str:
    """Replace the vanilla single-entry FileSystem block with a dual-entry block
    that explicitly mounts P:\\ (vanilla data) and P:\\<ModName>\\ (mod source).

    Vanilla gproj has:
        FileSystem {
         FileSystemPathClass {
          Name "Game Root"
          Directory "./"
         }
        }
    which is correct only when launched with cwd matching the gproj folder AND
    that folder containing all vanilla resources. Our scaffolded copy at
    P:\\<ModName>\\workbench\\dayz.gproj satisfies neither — Workbench resolves
    Directory relative to the gproj's parent folder, so "./" points at
    workbench/, where vanilla scripts/gui don't exist. Walking up with "../../"
    works for vanilla but doesn't make the mod source distinct from any other
    P:\\ folder. Mounting both as named entries is unambiguous.
    """
    new_block = (
        f'   FileSystem {{\n'
        f'    FileSystemPathClass {{\n'
        f'     Name "P Drive"\n'
        f'     Directory "P:/"\n'
        f'    }}\n'
        f'    FileSystemPathClass {{\n'
        f'     Name "{modname}"\n'
        f'     Directory "P:/{modname}/"\n'
        f'    }}\n'
        f'   }}'
    )
    return re.sub(
        r'^\s*FileSystem\s*\{[^}]*?FileSystemPathClass\s*\{[^}]*?\}\s*\}',
        new_block,
        text,
        count=1,
        flags=re.MULTILINE | re.DOTALL,
    )


def inject_mod_paths_into_gproj(text: str, modname: str) -> str:
    """For each module in WORKBENCH_MODULE_INJECTIONS, append the mod's
    matching scripts/<n>_X path to that module's Paths { ... } block.

    The vanilla file uses 1-space indentation and consistent block formatting,
    so a line-walking parser is more robust than regex against future tweaks.
    """
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        out.append(line)

        m = re.match(r'^(\s*)Name "([^"]+)"\s*$', line)
        if m and m.group(2) in WORKBENCH_MODULE_INJECTIONS:
            module_name = m.group(2)
            mod_path = f"{modname}/{WORKBENCH_MODULE_INJECTIONS[module_name]}"
            j = i + 1
            in_paths = False
            path_indent: str | None = None
            while j < len(lines):
                pline = lines[j]
                out.append(pline)
                if not in_paths:
                    if re.match(r"^\s*Paths\s*\{\s*$", pline):
                        in_paths = True
                else:
                    pm = re.match(r'^(\s*)"[^"]+"\s*$', pline)
                    if pm and path_indent is None:
                        path_indent = pm.group(1)
                    if re.match(r"^\s*\}\s*$", pline):
                        injection = f'{path_indent or "     "}"{mod_path}"\n'
                        out.insert(-1, injection)
                        j += 1
                        break
                j += 1
            i = j
            continue
        i += 1
    return "".join(out)


def make_dir_link(src: Path, dst: Path) -> str:
    """Create a directory symlink. Falls back to junction on Windows when symlinks need admin."""
    try:
        os.symlink(src, dst, target_is_directory=True)
        return "symlink"
    except OSError:
        if os.name == "nt":
            subprocess.run(
                ["cmd", "/c", "mklink", "/J", str(dst), str(src)],
                check=True, capture_output=True, text=True,
            )
            return "junction"
        raise


# Project-discovery marker. Written at P:\<ModName>\.agentic-z-project (which
# transparently lands inside the workspace via the junction). Contains the
# absolute path to the workspace project root. Used by /dayz-init's hub to
# discover ALL managed projects, not just the cached current one.
#
# This is a SEPARATE file from build-pbo's .agentic-z-scaffold marker (which
# lives at P:\Mods\@<ModName>\ and contains the modname for clean-workspace's
# ownership check). Different file, different location, different purpose.
PROJECT_MARKER = ".agentic-z-project"


def write_project_marker(p_drive_link: Path, project_root: Path) -> None:
    """Write P:\\<ModName>\\.agentic-z-project containing the project root path.

    Idempotent — overwrites if present (path may have moved since last run).
    Failure is non-fatal: the project still works, just won't show up in the
    /dayz-init hub's switch-project list.
    """
    marker = p_drive_link / PROJECT_MARKER
    try:
        marker.write_text(str(project_root.resolve()) + "\n", encoding="utf-8")
    except OSError as e:
        print(f"{WARN} Could not write project marker {marker}: {e}")
        print("       /dayz-init hub's switch-project won't see this mod.")


def _link_target(path: Path) -> Path | None:
    """Return the link target (without \\\\?\\ prefix) or None if the path is not a link."""
    try:
        target = os.readlink(path)
    except OSError:
        return None
    if target.startswith("\\\\?\\"):
        target = target[4:]
    return Path(target)


def _paths_equal(a: Path, b: Path) -> bool:
    return os.path.normcase(os.path.normpath(str(a))) == os.path.normcase(os.path.normpath(str(b)))


def _remove_link(path: Path) -> None:
    """Remove a directory link without descending into the target."""
    if os.name == "nt":
        subprocess.run(
            ["cmd", "/c", "rmdir", str(path)],
            check=True, capture_output=True, text=True,
        )
    else:
        path.unlink()


def check_or_clean_p_drive_link(p_drive_link: Path, workspace_target: Path) -> None:
    """Ensure P:\\<ModName>\\ is absent, or a stale junction we can safely remove.

    Refuses on a real folder or a junction pointing at a different location.
    Auto-cleans a junction that points at our about-to-be-created workspace path
    (typical case: a prior scaffold's workspace was deleted but the junction wasn't).
    """
    if not os.path.lexists(p_drive_link):
        return  # nothing there

    link_target = _link_target(p_drive_link)
    if link_target is None:
        sys.exit(
            f"{FAIL} {p_drive_link} exists as a real folder, not a link.\n"
            "       Refusing to clobber. Move or remove it manually and re-run."
        )

    if _paths_equal(link_target, workspace_target):
        try:
            _remove_link(p_drive_link)
        except subprocess.CalledProcessError as e:
            sys.exit(
                f"{FAIL} Could not remove stale link at {p_drive_link}\n"
                f"       {(e.stderr or '').strip()}"
            )
        print(f"{OK} Removed stale link at {p_drive_link} (target was missing)")
        return

    sys.exit(
        f"{FAIL} {p_drive_link} is a link pointing at {link_target}\n"
        "       Remove or rename it manually and re-run."
    )


def gate_on_preflight() -> None:
    """Every DayZ skill runs /dayz-preflight first and halts on non-zero exit."""
    if not PREFLIGHT.exists():
        sys.exit(
            f"{FAIL} dayz-preflight skill not found at "
            f"{PREFLIGHT.relative_to(REPO_ROOT)}"
        )
    result = subprocess.run([sys.executable, str(PREFLIGHT)])
    if result.returncode != 0:
        sys.exit(result.returncode)


def main() -> int:
    parser = argparse.ArgumentParser(description="Scaffold a new DayZ mod project.")
    parser.add_argument("modname", help="Mod name (also folder + CfgPatches class).")
    parser.add_argument("--author", help="Author handle (cached for future runs).")
    args = parser.parse_args()

    gate_on_preflight()
    validate_name(args.modname)
    author = resolve_author(args.author)

    workspace_target = WORKSPACE / args.modname
    p_drive_link = P_DRIVE / args.modname

    if workspace_target.exists():
        sys.exit(
            f"{FAIL} {workspace_target.relative_to(PROJECT_DIR)} already exists. Refusing to clobber."
        )
    check_or_clean_p_drive_link(p_drive_link, workspace_target)

    target = scaffold(args.modname, author)

    try:
        kind = make_dir_link(target, p_drive_link)
    except Exception as e:
        shutil.rmtree(target, ignore_errors=True)
        sys.exit(
            f"{FAIL} Failed to create P:\\{args.modname} junction: {e}\n"
            "       Scaffold rolled back."
        )
    print(f"{OK} P:\\{args.modname} {kind} -> {target.relative_to(PROJECT_DIR)}")

    write_project_marker(p_drive_link, target)

    rel = target.relative_to(PROJECT_DIR)
    print()
    print("Next steps:")
    print(f"  - Add Enforce Script files under {rel}/scripts/3_Game (or 4_World, 5_Mission)")
    print(f"  - Add models/textures/materials under {rel}/data")
    print(f"  - Add UI layouts under {rel}/gui")
    print(f"  - Open in Workbench: /dayz-launch-workbench --mod {args.modname}")
    print(f"  - When ready, /dayz-build-pbo to pack and deploy to P:\\Mods\\@{args.modname}\\Addons\\")
    return 0


if __name__ == "__main__":
    sys.exit(main())
