"""dayz-add-map: Set up a DayZ test map under workspace/_server/.

Copies the mission template from DayZ Server install if missing (or with
--refresh-mission), creates workspace/_server/maps/<map>/serverDZ.cfg and
profiles/. Idempotent.

This is the setup half of the local-test loop. /dayz-launch-test is the run
half and expects this setup to be in place.

See SKILL.md for full usage.
"""
from __future__ import annotations

import argparse
import importlib.util
import shutil
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

REPO_ROOT = Path(__file__).resolve().parents[3]
WORKSPACE = REPO_ROOT / "workspace"
PREFLIGHT_DIR = REPO_ROOT / ".claude" / "skills" / "dayz-preflight"
PREFLIGHT = PREFLIGHT_DIR / "preflight.py"
SERVER_ROOT = WORKSPACE / "_server"
MISSIONS_DIR = SERVER_ROOT / "missions"
MAPS_DIR = SERVER_ROOT / "maps"

KNOWN_MAPS: dict[str, str] = {
    "chernarus": "dayzOffline.chernarusplus",
    "livonia": "dayzOffline.enoch",
    "sakhal": "dayzOffline.sakhal",
}

OK = "[OK]   "
WARN = "[WARN] "
FAIL = "[FAIL] "


def _load_preflight_module():
    spec = importlib.util.spec_from_file_location("dayz_preflight_module", PREFLIGHT)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load preflight module at {PREFLIGHT}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_preflight = _load_preflight_module()
find_dayz_server = _preflight.find_dayz_server


def gate_on_preflight() -> None:
    if not PREFLIGHT.exists():
        sys.exit(f"{FAIL} dayz-preflight skill not found at {PREFLIGHT.relative_to(REPO_ROOT)}")
    result = subprocess.run([sys.executable, str(PREFLIGHT)])
    if result.returncode != 0:
        sys.exit(result.returncode)


def resolve_mission_template(map_name: str) -> str:
    return KNOWN_MAPS.get(map_name, map_name)


def ensure_mission(template: str, refresh: bool) -> None:
    """Ensure workspace/_server/missions/<template>/ exists.

    Copies from DayZ Server install if missing or if `refresh` is True.
    """
    dest = MISSIONS_DIR / template
    already_present = dest.exists() and any(dest.iterdir())

    if already_present and not refresh:
        print(f"{OK} Mission already present: {dest.relative_to(REPO_ROOT)}")
        return

    server_root = find_dayz_server()
    if server_root is None:
        sys.exit(
            f"{FAIL} DayZ Server install not found.\n"
            "       Required to copy mission templates. Install via Steam (Tools section,\n"
            "       free, appid 223350), or manually populate\n"
            f"       {dest.relative_to(REPO_ROOT)} with mission content."
        )

    src = server_root / "mpmissions" / template
    if not src.exists():
        available = []
        mp = server_root / "mpmissions"
        if mp.exists():
            available = sorted(p.name for p in mp.iterdir() if p.is_dir())
        avail_str = "\n".join(f"          {n}" for n in available) or "          (none)"
        sys.exit(
            f"{FAIL} Mission template '{template}' not found in DayZ Server install at\n"
            f"       {src}\n"
            f"       Available templates in DayZ Server's mpmissions/:\n{avail_str}"
        )

    MISSIONS_DIR.mkdir(parents=True, exist_ok=True)
    if dest.exists():
        shutil.rmtree(dest)
        action = "Refreshed"
    else:
        action = "Copied"
    shutil.copytree(src, dest)
    print(f"{OK} {action} {dest.relative_to(REPO_ROOT)}  (from DayZ Server install)")


def setup_map_dir(map_name: str, template: str) -> None:
    """Ensure workspace/_server/maps/<map>/ has serverDZ.cfg + profiles/."""
    map_dir = MAPS_DIR / map_name
    profile_dir = map_dir / "profiles"
    profile_dir.mkdir(parents=True, exist_ok=True)

    cfg_path = map_dir / "serverDZ.cfg"
    if not cfg_path.exists():
        cfg_path.write_text(default_server_cfg(map_name, template), encoding="utf-8")
        print(f"{OK} Wrote default {cfg_path.relative_to(REPO_ROOT)}")
    else:
        cfg = cfg_path.read_text(encoding="utf-8")
        if "allowFilePatching" not in cfg:
            cfg = cfg.rstrip() + "\nallowFilePatching = 1;\n"
            cfg_path.write_text(cfg, encoding="utf-8")
            print(f"{OK} Appended allowFilePatching = 1 to {cfg_path.relative_to(REPO_ROOT)}")
        else:
            print(f"{OK} {cfg_path.relative_to(REPO_ROOT)} unchanged (already configured)")

    print(f"{OK} {profile_dir.relative_to(REPO_ROOT)} ready")


def default_server_cfg(map_name: str, template: str) -> str:
    return dedent(
        f"""\
        // DayZ server config for map: {map_name} (mission: {template})
        // Generated by /dayz-add-map. Edit freely — the skill won't overwrite this once
        // it exists, but it WILL re-add `allowFilePatching = 1;` if you remove it
        // (clients launch with -filePatching and the server refuses connection without
        // this setting).
        hostname        = "Local Test ({map_name})";
        password        = "";
        passwordAdmin   = "";
        maxPlayers      = 4;
        verifySignatures = 0;
        forceSameBuild  = 0;
        allowFilePatching = 1;
        disableVoN      = 0;
        disable3rdPerson = 0;
        instanceId      = 1;
        persistent      = 0;

        class Missions
        {{
            class DayZ
            {{
                template = "{template}";
            }};
        }};
        """
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Set up a DayZ test map under workspace/_server/.")
    parser.add_argument(
        "map",
        help=(
            f"Map name. Known aliases: {', '.join(KNOWN_MAPS)}. "
            "Custom missions: pass the mission folder name (e.g. dayzOffline.namalsk)."
        ),
    )
    parser.add_argument(
        "--refresh-mission",
        action="store_true",
        help="Re-copy the mission folder from DayZ Server install, overwriting local edits.",
    )
    args = parser.parse_args()

    gate_on_preflight()
    print()

    template = resolve_mission_template(args.map)
    print(f"{OK} Mission: {template}")

    ensure_mission(template, refresh=args.refresh_mission)
    setup_map_dir(args.map, template)

    print()
    print(f"Map '{args.map}' is ready. Next:")
    print(f"  /dayz-build-pbo <ModName>     (build the mod)")
    print(f"  /dayz-launch-test <ModName> --map {args.map}    (launch)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
